name: Azure ARM template deployment
on:
  push:
    paths:
    - 'templates/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@master

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./templates/azuredeploy.json
        parameters: ./templates/azuredeploy.parameters.json adminPassword=${{ secrets.ADMIN_PASSWORD }} userObjectId=${{ secrets.USER_OBJECT_ID }} userUpn=${{ secrets.USER_UPN }} alias=${{ secrets.USER_ALIAS }}

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}
